sudo: required
services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root test < tests/db.sql
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

jobs:
  include:
    - name: Nette Code Checker
      install:
        - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      script:
        - php temp/code-checker/code-checker --strict-types
      language: php
      php:
        - 7.1


    - name: Nette Coding Standard
      install:
        - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
      script:
        - php temp/coding-standard/ecs check src examples --config temp/coding-standard/coding-standard-php71.yml
      language: php
      php:
        - 7.1


    - name: PHP 7.1
      install:
        - travis_retry composer require nette/tester --dev
      script:
        - vendor/bin/tester -c tests/php.linux.ini tests -s
      before_script:
        - bash tests/bash/setup.sh
        - bash tests/bash/db.sh
      language: php
      php:
        - 7.1


    - name: PHP 7.2
      install:
        - travis_retry composer require nette/tester --dev
      script:
        - vendor/bin/tester -c tests/php.linux.ini tests -s
      before_script:
        - bash tests/bash/setup.sh
        - bash tests/bash/db.sh
      language: php
      php:
        - 7.2


    - name: PHP 7.3
      install:
        - travis_retry composer require nette/tester --dev
      script:
        - vendor/bin/tester -c tests/php.linux.ini tests -s
      before_script:
        - bash tests/bash/setup.sh
        - bash tests/bash/db.sh
      language: php
      php:
        - 7.3


    - stage: Code Coverage
      script:
        - vendor/bin/tester -c tests/php.linux.ini -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml
      before_script:
        - bash tests/bash/setup.sh
        - bash tests/bash/db.sh
      language: php
      php:
        - 7.1
