<?php

declare(strict_types=1);

namespace Drago\Generator\Generator;

use Dibi\Exception;
use Drago\Generator\Base;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;
use Nette\Utils\FileSystem;
use Nette\Utils\Strings;
use Throwable;


/** Generates data class based on database schema. */
class DataClassGenerator extends Base implements IGenerator
{
	/**
	 * Runs the generation process for a specific table or all tables.
	 * @throws Exception
	 * @throws Throwable
	 */
	public function runGeneration(?string $table = null): void
	{
		if ($table !== null) {
			$this->createPhpFile($table);
		} else {
			foreach ($this->repository->getTableNames() as $table) {
				$this->createPhpFile($table);
			}
		}
	}


	/**
	 * Creates a PHP file for a given table.
	 * @throws Exception
	 * @throws Throwable
	 */
	public function createPhpFile(string $table): void
	{
		$options = $this->options;
		$name = $this->filename($table, $options->suffixDataClass);
		$class = new ClassType($name);

		if ($options->finalDataClass) {
			$class->setFinal();
		}

		if ($options->extendsOn) {
			$class->setExtends($options->extendsDataClass);
		}

		$references = $this->getReferencesTable($table);

		foreach ($this->repository->getColumnNames($table) as $column) {
			if ($options->lower) {
				$column = Strings::lower($column);
			}

			$this->validateColumn($table, $column);
			$attr = $this->repository->getColumn($table, $column);

			if ($options->constantDataClass) {
				$constant = $options->constantDataPrefix
					? $options->constantDataPrefix . $this->inflector->classify($column)
					: $this->inflector->classify($column);

				$class->addConstant($constant, $column)
					->setType('string')
					->setPublic();

				if ($options->constantSizeDataClass && !$attr->isAutoIncrement() && $attr->getSize() > 0) {
					$class->addConstant($constant . 'Size', $attr->getSize())
						->setType('int')
						->setPublic();
				}
			}

			$detectType = $this->detectType($attr->getNativeType());
			$class->addProperty($column)
				->setType($detectType)
				->setNullable($attr->isNullable())
				->setInitialized($attr->isNullable())
				->setPublic();

			if ($options->referencesDataClass && isset($references[$column])) {
				$filename = $this->filename($references[$column], $options->suffixDataClass);
				$class->addProperty($references[$column])
					->setType($options->namespaceDataClass . '\\' . $filename);
			}
		}

		$file = new PhpFile;
		$file->addComment('This file was generated by Drago Generator.')
			->setStrictTypes()
			->addNamespace($options->namespaceDataClass)
			->addUse('Drago')
			->add($class);

		$path = $options->pathDataClass . '/' . $name . '.php';
		FileSystem::write($path, $file->__toString());
	}
}
