name: Tests

on: [push, pull_request]

env:
    php-extensions: iconv, json, mbstring, xml, gd, intl, tokenizer, mysqli
    php-tools: "composer:v2"

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0']

            fail-fast: false

        name: PHP ${{ matrix.php }} tests

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd "mysqladmin ping -ppass"
                    --health-interval 10s
                    --health-start-period 10s
                    --health-timeout 5s
                    --health-retries 10

        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.php-extensions }}
                  tools: ${{ env.php-tools }}
                  coverage: none

            - name: MySQL database
              run: |
                sudo apt-get install -y mysql-client
                mysql --host 127.0.0.1 --port 3306 -uroot -proot test < tests/db.sql

            - run: composer install --no-progress --prefer-dist
            - run: vendor/bin/tester -p phpdbg tests -s -C --coverage ./coverage.xml --coverage-src ./src
            - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
            - env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: php php-coveralls.phar --verbose --config tests/.coveralls.yml
